services:
  proxy:
    image: nginx
    container_name: easy_book_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - /var/log/nginx:/var/log/nginx
    networks:
      - easy_book_network

networks:
  easy_book_network:
    driver: bridge
