version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner

jobs:
  runner:
    resource_class: alqae/linode
    machine: true
    steps:
      - checkout
      - run:
          name: Stop containers
          command: docker compose down
      - run:
          name: Start containers
          command: docker compose up -d
      - run:
          name: Verify containers
          command: docker compose ps
