version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner

jobs:
  runner:
    resource_class: alqae/linode
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Show User Information
          command: |
            pwd  # Verifica el directorio actual
            ls -a  # Verifica los archivos del directorio actual
            whoami  # Verifica el usuario que está ejecutando el workflow
            id  # Verifica los grupos a los que pertenece el usuario, incluyendo docker
      - run:
          name: Verify Docker Permissions
          command: |
            docker --version  # Verifica que el comando docker esté disponible
            docker ps  # Verifica que el usuario tenga permisos para ejecutar comandos docker
