version: 2.1
workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: alqae/linode
    steps:
      - run: echo $(pwd)
      - run: echo $(ls -a)
      - run: docker ps -a